name: Mirror to Bitbucket

on:
  push:
    branches: ["main"]   # cualquier rama
    tags: ["**"]       # cualquier tag
  workflow_dispatch: {}  # opcional: correrlo a mano

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # trae todo el historial y tags

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Agregar remoto Bitbucket
        env:
          BB_USER: "x-bitbucket-api-token-auth"
          BB_PASS: "ATATT3xFfGF0S49kz89bcr75Qj_ozzH0__g7z65ZJ3nSUVJzyEAqQ5jSxWC03vRRP4FZ17PJYPfYhXMtEkhX4eiIUITGBar0X8OY4EFRESocnPYt8n2WkjG15MDHbuYxX1_6Cjoo3twjeMwHYLNnznW-TyXs0cjtyPaDHpz1wxK7CYyk0txHYnA=EC9EA29B"
          BB_REMOTE: "https://bitbucket.org/genitsrl/al2-android.git" # https://bitbucket.org/<workspace>/<repo>.git
        run: |
          git config user.email 9z3zbob9idck1hrysweht46gidzf66@bots.bitbucket.org
          git remote add bitbucket "https://x-token-auth:${BB_PASS}@bitbucket.org/genitsrl/al2-android.git"
          git push bitbucket --all --prune
          git push bitbucket --tags --prune

      # (Opcional) Si usás LFS, descomentá:
      # - name: Git LFS push
      #   run: |
      #     git lfs install
      #     git lfs fetch --all
      #     git lfs push bitbucket --all
